/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.abc.ui;

import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;
/**
 *
 * @author USER
 */
public class MyJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MyJFrame
     */
    public MyJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        openMenu = new javax.swing.JMenu();
        exitMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jScrollPane1.setViewportView(jTable);

        openMenu.setText("開檔");
        openMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                openMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(openMenu);

        exitMenu.setText("離開");
        jMenuBar1.add(exitMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openMenuMouseClicked
        //---------------------------------------------
        //在MenuBar中的[開檔]被點擊時	
        //---------------------------------------------     
        //開啟FileChooser物件
        JFileChooser jFileChooser = new JFileChooser();
        jFileChooser.setDialogTitle("開啟檔案");

        //如果有選擇檔案  
        int returnVal = jFileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            try{
                //設定檔案物件
                File file = jFileChooser.getSelectedFile();                    

                //產生一個JSON解析物件	
                JSONParser parser = new JSONParser();

                //將檔案內容解析成JSON物件(可能是JSONArray或JSONObject)
                Object obj = parser.parse(new FileReader(file));        

                //將obj轉成JSONArray陣列物件   
                JSONArray items = (JSONArray)obj;

                //清除原有資料
                DefaultTableModel model = (DefaultTableModel) jTable.getModel();
                model.setRowCount(0);             

                //將JSON陣列物件逐個取出   
                for(Object item : items) {
                    //每個取出物件轉成JSON物件
                    JSONObject jsonItem = (JSONObject) item;

                    //================================================
                    //取出JSON物件中的資料(名稱, 型態, 緯度, 經度)
                    //================================================   
                    String id = (String) jsonItem.get("id");
                    String name = (String) jsonItem.get("name");
                    String line = (String) jsonItem.get("line");
                    String address = (String) jsonItem.get("address");
                    double latitude = (double) jsonItem.get("latitude");
                    double longitude = (double) jsonItem.get("longitude");
                    //================================================ 

                    //將取出的檔位產生一個陣列
                    Object[] row = {id, name, line, address, latitude, longitude};        

                    //將產生的陣列加入表格的資料物件中
                    model.addRow(row);
                    //=========================================                        
                }          
            }catch(IOException ex) {
                JOptionPane.showMessageDialog(this, "讀檔時發生錯誤!");
            }catch(ParseException ex) {
                JOptionPane.showMessageDialog(this, "JSON格式解析錯誤!");                
            }    
        } else {
            System.out.println("取消檔案讀取");
        }             
        //---------------------------------------------   
    }//GEN-LAST:event_openMenuMouseClicked

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu exitMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JMenu openMenu;
    // End of variables declaration//GEN-END:variables
}
