/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.abc.ui;

import static com.abc.Activity.dateTime;
import com.abc.GroupSignUp;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class MyJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MyJFrame
     */
    public MyJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        openMenu = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "null", "Title 6"
            }
        ));
        jScrollPane1.setViewportView(jTable);

        openMenu.setText("File");
        openMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                openMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(openMenu);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openMenuMouseClicked
        //---------------------------------------------
        //在MenuBar中的Open被點擊時	
        //---------------------------------------------     
        //開啟FileChooser物件
        JFileChooser jFileChooser = new JFileChooser();
        jFileChooser.setDialogTitle("開啟檔案");

        //如果有選擇檔案   
        int returnVal = jFileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            //設定檔案物件
            File file = jFileChooser.getSelectedFile();

            //逐筆讀取檔案內容	
            try {
                //產生一個BufferedReader物件, 用來逐筆讀取檔案	
                BufferedReader b = new BufferedReader(new FileReader(file));

                //存放每次讀入的單行內容		
                String data; 

                //清除原有資料
                DefaultTableModel model = (DefaultTableModel) jTable.getModel();
                model.setRowCount(0); 

                //=======================================================
                // (1)建立一個存放所有團體報名物件的arrayList
                //=======================================================
                ArrayList<GroupSignUp> arrayList = new ArrayList();
                //=======================================================

                while ((data = b.readLine()) != null) {
                    //切割逗號分隔的項目
                    String items[]=data.split(",", -1);

                    //=========================================
                    // (2)取出電話, 性別, 參加人數, 租用相機數
                    //=========================================
                    String tel = items[0];
                    String name = items[1];
                    int totalPeople = Integer.parseInt(items[2]);
                    int totalCamera = Integer.parseInt(items[3]);            
                    //=========================================  

                    //====================================================================
                    // (3)產生一個團體報名物件, 將它加入arrayList中
                    //====================================================================
                    arrayList.add(new GroupSignUp(tel, name, totalPeople, totalCamera));          
                    //====================================================================
                }  


                //==========================================================================
                // (4)逐個取出團體報名物件, 再取出其內資料, 加入表格中顯示
                //==========================================================================
                for(int i=0; i<arrayList.size(); i++){
                    //取出arrayList中的第i個銷貨收入物件
                    GroupSignUp s = arrayList.get(i);

                    //將取出的欄位產生一個陣列
                    Object[] row = {dateTime, s.getTel(), s.getName(),s.getTotalPeople(),s.getTotalCamera(),s.fee()};

                    //將產生的陣列加入表格中
                    model.addRow(row);
                }
                //==========================================================================        
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "讀檔時發生錯誤!");
            }
        } else {
            System.out.println("取消檔案讀取");
        }         
        //---------------------------------------------    
    }//GEN-LAST:event_openMenuMouseClicked

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JMenu openMenu;
    // End of variables declaration//GEN-END:variables
}
